# Dockerfile.test

FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN apt-get update 
RUN apt-get -y install gcc
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . .
CMD ["pytest"]
