name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint --output-format=text $(git ls-files '*.py') || true

      - name: Get Pylint report
        id: pylint-report
        run: |
          pylint --output-format=parseable $(git ls-files '*.py') > pylint_report.txt || true
        continue-on-error: true

      - name: Check Pylint Coverage
        run: |
          coverage=$(grep -E -o '^Your code has been rated at [0-9.]+/10' pylint_report.txt | awk -F'/' '{print $1}')
          echo "::set-output name=coverage::$coverage"

      - name: Publish Pylint Coverage
        run: |
          echo "Pylint Coverage: ${{ steps.pylint-report.outputs.coverage }}"
